apiVersion: v1
kind: Service
metadata:
  name: prf-service
spec:
  selector:
    app: profile-dev
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 31000