const ACCESS_TOKEN_SECRET_KEY = "1kjahsbuy612"
const REFRESH_TOKEN_SECRET_KEY = "asdkajsboi12"
const ACCESS_TOKEN_EXP = 12
const REFRESH_TOKEN_EXP = 24

export {
    ACCESS_TOKEN_EXP,
    REFRESH_TOKEN_EXP,
    REFRESH_TOKEN_SECRET_KEY,
    ACCESS_TOKEN_SECRET_KEY
}